### PR TITLE
Trim values to fit the columns

### PR DESCRIPTION
**Pull request by stefansjfw**
Looks like this now:

```
Scan Summary:
Scan start time               Fri Jun 11 10:43:27 CEST 2021           
Scan duration                 1.165055s                               
Total violations found        89                                      

Scan Per-policy Details:
Policy name                   CIS Amazon Web Services Foundations     
No. of violations             89                                      
Violations                    
  Resource ID                                                 Rule GUID                                         Rule name                                                   
  AWS::IAM::Account:aws-global:321859670049                   68a347b3-091c-4421-97a4-abc29b8f22e2              Ensure IAM password policy requires at least one upperca... 
  AWS::IAM::Account:aws-global:321859670049                   a26f7700-3552-4845-8f9b-361d733c2bb0              Ensure IAM password policy requires at least one lowerca... 
  AWS::IAM::Account:aws-global:321859670049                   9ddf54f7-b8cd-4d3d-8003-08777d8ce8c9              Ensure IAM password policy require at least one symbol      
  AWS::IAM::Account:aws-global:321859670049                   9a63958d-1d15-4e26-8604-2004b32c9be7              Ensure IAM password policy require at least one number      
  AWS::IAM::Account:aws-global:321859670049                   132f680e-7819-432c-9259-2210c2e947dd              Ensure IAM password policy requires minimum length of 14... 
  AWS::IAM::Account:aws-global:321859670049                   463947f9-fafa-4fa1-88a5-dab855928bca              Ensure IAM password policy prevents password reuse          
  AWS::IAM::Account:aws-global:321859670049                   12ac08c9-9309-44d4-b6ae-98d15db5becd              Ensure IAM password policy expires passwords within 90 d... 
  arn:aws:iam::321859670049:user/FirehoseTest                 a992d086-cbd8-4c12-ac77-0fec98703037              Ensure IAM policies are attached only to groups or roles    
  arn:aws:iam::321859670049:user/Janea                        a992d086-cbd8-4c12-ac77-0fec98703037              Ensure IAM policies are attached only to groups or roles    
  arn:aws:iam::321859670049:user/TestUser                     a992d086-cbd8-4c12-ac77-0fec98703037              Ensure IAM policies are attached only to groups or roles    
  arn:aws:iam::aws:policy/AdministratorAccess                 8f0d6f07-5c32-4a25-8b25-6ca4c2198197              Ensure IAM policies that allow full "*:*" administrative... 
  arn:aws:cloudtrail:us-east-1:487193801865:trail/openrave... 3f2a6c76-edd8-4e6f-b0e1-5213acbfebda              Ensure CloudTrail trails are integrated with CloudWatch ... 
  arn:aws:cloudtrail:us-east-1:487193801865:trail/openrave... 10b14b8e-f19d-4f8e-bcf1-d9a7b701ea59              Ensure S3 bucket access logging is enabled on the CloudT... 
  arn:aws:kms:us-east-1:321859670049:key/b005df98-5fc9-408... 379ea727-2b8c-420b-9933-3a157707b931              Ensure rotation for customer created CMKs is enabled        
  arn:aws:kms:us-east-2:321859670049:key/f1f4da7f-6d44-498... 379ea727-2b8c-420b-9933-3a157707b931              Ensure rotation for customer created CMKs is enabled        
  arn:aws:kms:us-west-2:321859670049:key/80556388-386f-4ec... 379ea727-2b8c-420b-9933-3a157707b931              Ensure rotation for customer created CMKs is enabled        
  arn:aws:ec2:fips-us-east-1:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t... 
  arn:aws:ec2:fips-us-east-1:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t... 
  arn:aws:ec2:fips-us-east-1:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t... 
  arn:aws:ec2:fips-us-east-1:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t... 
  arn:aws:ec2:fips-us-east-2:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t... 
  arn:aws:ec2:fips-us-west-2:321859670049:security-group/s... f3ffdd5a-cb43-4da3-9036-222cfd294a2c              Ensure no security groups allow ingress from 0.0.0.0/0 t...

### CODE REVIEW

**Comment by stefansjfw** [comment]
@kickroot Not sure about trimming the resource ID column. User can't do much with partial resource ID if wants to remediate the rule. WDYT?

**Comment by stefansjfw** [comment]
@kickroot Not sure about trimming the resource ID column. User can't do much with partial resource ID if wants to remediate the rule. WDYT?

**Comment by kickroot** [comment]
Trim the first x characters as needed (instead of the last x characters) to fit in the `...`  We need to keep the columns lined up.

It's a tough problem with console output.  When we offer other formats (CSV, JSON, etc) we can use the entire sting.

**Comment by stefansjfw** [comment]
@kickroot 
image

**Comment by kickroot** [comment]
Looks good to me :+1:

**Review by kickroot — APPROVED** [review]

**Pull request merged**
