### PR TITLE
Cpsm main merge

### PR DESCRIPTION
**Pull request by PrzemyslawTusinski**

### CODE REVIEW

**Comment by PrzemyslawTusinski** [comment]
Is that correct way to merge main into cpsm and it won't cause any issue? 
I'm not sure please provide feedback

**Comment by stefansjfw** [comment]
I'd say just rebasing cspm on top of main would be a cleaner way of doing this. Would end up with same result though

**Review by kickroot — APPROVED** [review]
Thanks for fixing this, this bug actually bit me today in my testing.

**Comment by PrzemyslawTusinski** [comment]
@stefansjfw Then I would have to force-push (possibly breaking derived branches history???)

**Comment by stefansjfw** [comment]
> @stefansjfw Then I would have to force-push (possibly breaking derived branches history???)
> Am I getting this right?

rebasing would probably require force-push yes, merging main directly wouldn't (i.e. no need for cspm-main-merge). It's fine this way too, as main will be our final branch in the end, not cspm  (forgot to approve :) )

**Review by stefansjfw — APPROVED** [review]

**Review by belosh59 — APPROVED** [review]

**Pull request merged**
