### PR TITLE
#201 - Initial proposal with static OutputImpl factory

### PR DESCRIPTION
**Pull request by belosh59**
Next commit for the plugin version

### CODE REVIEW

**Comment by belosh59** [comment]
Build would be failed so far, while magpie-api is not merged

**Comment by curphey** [comment]
Assigned to @kickroot to review

**Comment by belosh59** [comment]
As discussed with @kickroot we will decouple producer and consumer side of ScanResults by serializing payloads to json, and forcing consumers (output-plugin) to deserialize payload as per their needs and required contract

**Comment by belosh59** [comment]
Leftovers:
- minor refactoring. Proper shutdown
- config processing for output plugins
- csv output enabling

**Comment by belosh59** [comment]
All leftovers has been resolved. PR is ready for review @kickroot

**Review by kickroot — APPROVED** [review]

**Pull request merged**
